name = "EnergyProjectMDP"
uuid = "53679376-3f09-42e6-a4dd-a5b90ab113ce"
authors = ["mansurarief <ariefm@stanford.edu>", "riyakinnarkar <riyakinnarkar@gmail.com>"]
version = "0.1.0"

[deps]
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
